name: "Pull request workflow"

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.event.pull_request.number }}-pull-request
  cancel-in-progress: true

jobs:
  linter:
    name: "Linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up JDK 17"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "KtLint"
        run: ./gradlew --continue ktLintCheck

  test:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up JDK 17"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "Run unit tests"
        run: ./gradlew test

#  test:
#    name: "Unit tests"
#    runs-on: ubuntu-latest
#    needs: setup
#    steps:
#      - uses: actions/checkout@v4
#      - name: "Set up JDK 17"
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#      - name: "Download google-services.json"
#        uses: actions/download-artifact@v4
#        with:
#          name: google-services
#          path: ./app
#      - name: "Download local.properties"
#        uses: actions/download-artifact@v4
#        with:
#          name: local-properties
#          path: .
#
#
